### ISSUE TITLE
308 status : Number of redirects hit maximum amount with Nginx and docker on a ubuntu VPS

### ISSUE THREAD

**Issue by mowabidev** [dunglas/mercure#1025]
I'm trying to put Mercury into production on a VPS server (ubuntu 22.04 and Nginx) using Docker. But when I start the container and try to access the Mercury UI, it returns a 308 status : Number of redirects hit maximum amount.

Can anyone help?

Here's my nginx:

```
server {
    server_name mercure.mydomain.com;

    location / {
        proxy_pass http://localhost:3001;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Enable fast reply in SSE
        proxy_buffering off;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 24h;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mercure.mydomain.com/fullchain.pem; >
    ssl_certificate_key /etc/letsencrypt/live/mercure.mydomain.com/privkey.pem>
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mercure.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name mercure.mydomain.com;
    return 404; # managed by Certbot

}
```

And here's my docker configuration:
```
services:
  mercure:
    container_name: "mercure"
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      
      - MERCURE_PUBLISHER_JWT_KEY="The key"
      - MERCURE_SUBSCRIBER_JWT_KEY="The key"
      
      - MERCURE_CORS_ALLOWED_ORIGINS=*
      - MERCURE_PUBLISH_ALLOWED_ORIGINS=*
      
      - MERCURE_EXTRA_DIRECTIVES=anonymous
      - MERCURE_UI=1
    ports:
      - "3001:80"
    volumes:
      - mercure_data:/data

volumes:
  mercure_data: {}
```

Your help is most welcome. Thank you.

**Comment by mowabidev** [comment]
Hello,
I found out what was wrong. I had to add `SERVER_NAME=:80` in the docker-compose. It's working fine now and /heathz is returning the 200 response.
But I notice that I still can't access /.well-known/mercure/ui. Is this not possible in production?
Here's my docker configuration : 
```
services:
  mercure:
    container_name: "mercure"
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      - MERCURE_PUBLISHER_JWT_KEY="The key"
      - MERCURE_SUBSCRIBER_JWT_KEY="The key"
      - SERVER_NAME=:80
      - MERCURE_CORS_ALLOWED_ORIGINS=*
      - MERCURE_PUBLISH_ALLOWED_ORIGINS=*
      - MERCURE_EXTRA_DIRECTIVES=demo
    ports:
      - "3001:80"
    volumes:
      - mercure_data:/data

volumes:
  mercure_data: {}
```
