### ISSUE TITLE
[Question] Symfony cloud integration

### ISSUE THREAD

**Issue by vbourdeix** [dunglas/mercure#127]
What would be the best and/or the simplest way to integrate mercure in a Symfony Cloud hosted project ?

**Comment by dunglas** [comment]
Currently, you can simply configure SymfonyCloud to run the Go binary using this template as an example: https://github.com/platformsh/template-golang/blob/master/.platform.app.yaml. But we're working on something better, stay tuned!

**Comment by MarioZ2002** [comment]
I already tried to run it as a golang app on Platform.sh. I was not able to get it working because of their write protected file system and they don't support bbolt databases as services.

@dunglas Will this you are working on also work with Platform.sh?

**Comment by tucksaun** [comment]
Golang apps are easy to run on SymfonyCloud. We lack this documentation but you can use the following snippet (`.symfony.cloud.yaml`) as a starting point:

```
name: app

# This actually has no importance
type: golang:1.10

build:
    flavor: 'none'

variables:
    env:
        DB_PATH: data/updates.db
        # This one should be defined using `var:set` instead of hardcoded
        JWT_KEY: 'myJWTKey'

web:
    upstream:
        socket_family: tcp
        protocol: http
    commands:
        start: ADDR=":${PORT}" ./mercure
    locations:
        /:
            allow: false
            passthru: true

disk: 2048

mounts:
    '/data': 'shared:files/data'

hooks:
    build: |
        set -e -x

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        curl -s -H 'Accept: application/octet-stream' -J -L "https://github.com/dunglas/mercure/releases/download/v0.6.0/mercure_0.6.0_Linux_x86_64.tar.gz" | tar -C /app/ -zxpf -
```

(In your context, you are probably going to need a [multiple applications project](https://symfony.com/doc/master/cloud/cookbooks/multi-apps.html) to get a Symfony app and the Mercure Hub deployed next to each other.
