### ISSUE TITLE
How to run Mercure in production with apache, symfony and docker?

### ISSUE THREAD

**Issue by undersound** [dunglas/mercure#157]
I am trying to run a symfony application together with mercure hub under https. 
**Symfony**, the **mysql db** and the **mercure hub** are all docker containers. 
I am using **mod_proxy** in apache on the host to proxy traffic to the symfony container.

I have the following docker compose settings for the mercure hub:

```  
mercure-hub:
    build:
      context: .
      dockerfile: build//hub/Dockerfile
    restart: always
    container_name: mercure-hub
    image: myimage-mercure-hub
    ports:
      - 3030:80
    environment:
      JWT_KEY: aVerySecretKey
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: '*'
      CORS_ALLOWED_ORIGINS: '*'
    expose:
      - 3030
```
The following vhost conf for the proxypass to the symfony container

```
<IfModule mod_ssl.c>
	<VirtualHost *:443>
		ProtocolsHonorOrder On
		Protocols h2 http/1.1

		ServerName http://example.com

		ProxyPreserveHost On
		ProxyPass / http://localhost:8099/
		ProxyPassReverse / http://localhost:8099/

		ServerAlias example.com

		Include /etc/letsencrypt/options-ssl-apache.conf
		SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
		SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

	</VirtualHost>
</IfModule>
```
And the vhost for port 80
```
<VirtualHost *:80>
	ProtocolsHonorOrder On
	Protocols h2 http/1.1

	ServerName http://example.com

	ProxyPreserveHost On
	ProxyPass / http://localhost:8099/
	ProxyPassReverse / http://localhost:8099/
</VirtualHost>
```

Now when I browser to https://example.com I get the following error
https://example.com:3030/hub?topic=my.topic net::ERR_SSL_PROTOCOL_ERROR

This is caused by the call in my app.js file from symfony. 

What am I doing wrong here?

Thanks in advance for any help
