### ISSUE TITLE
401 Unauthorized in DEMO mode

### ISSUE THREAD

**Issue by maximsamoilov** [dunglas/mercure#176]
Hi! I'm trying test demo mercure.

My host is Win7

I have vagrant where docker is installed.

```
my vagrantfile
`Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end
    config.vm.network "private_network", ip: "192.168.22.12"
    # config.vm.network "public_network"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder ".", "/var/www"
    config.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y git unzip wget
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        # or try apt install docker.io?
        usermod -aG docker vagrant
        apt install docker-compose -y
        dpkg -r --force-depends golang-docker-credential-helpers

        # enable color in console
        sed -i -r 's/#force_/force_/' /home/vagrant/.bashrc

        mkdir -p /var/www/persistent-data

        cd /var/www/docker/php
        docker build -t custom_php:1.0 ./
        cd ../
    SHELL
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        cd /var/www/docker
        su vagrant
        docker-compose up --build --force-recreate -d
    SHELL
end
```

my docker-compose
```
version: "3.3"

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    command: nginx -g "daemon off;"
    restart: always
    volumes:
      - /var/www/docker/nginx/snippets:/etc/nginx/snippets
      - /var/www/docker/nginx/conf.d:/etc/nginx/conf.d
      - type: bind
        source: ../code
        target: /var/www/html
    ports:
      - "80:80"

  php:
    container_name: php
    build:
      context: ./phpxdebug
    restart: always
    user: "1000:50"
    # environment:
    #   - database=joomla
    #   - db_user=db_user
    #   - db_password=db_user_password
    volumes:
      - /var/www/docker/php/custom.ini:/.user.ini
      - type: bind
        source: ../code
        target: /var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"

  mysql:
    container_name: database
    image: mysql
    restart: always
    user: "1000:50"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci',
              '--default-authentication-plugin=mysql_native_password', "--innodb_use_native_aio=0"]
    volumes:
      - /var/www/persistent-data/mysql-data:/var/lib/mysql
      - /var/www/docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "13306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: pma
      PMA_PASSWORD: nRKv5cdE&Prd@9HQNB
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"

  mercure:
    container_name: mercure
    image: dunglas/mercure
    environment:
      # - CERT_FILE=/cert/cert.crt
      # - CERT_KEY=/cert/cert.key
      - JWT_KEY=!ChangeMe!
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - DEMO=1
    ports:
      - "3080:80"
      # - "3443:443"
    # volumes:
      # - ./docker/mercure/cert.crt:/cert/cert.crt
      # - ./docker/mercure/cert.key:/cert/cert.key
```

in win7 /hosts
`192.168.22.12 translate.symfony.demp`

I try open http://translate.symfony.demp:3080/ it is fine, but when I click Discover then Subscribe and then Publish I get 401

JWT: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.obDjwCgqtPuIvwBlTxUEmibbBf0zypKCNzNKP7Op2UM`
payload: 
```
{
  "mercure": {
    "publish": ["*"]
  }
}
```

What do I do wrong? Could anybody help me?
