### ISSUE TITLE
/ works, but /hub 404 Not Found

### ISSUE THREAD

**Issue by stephanvierkant** [dunglas/mercure#210]
I'm running on a Symfony/API Platform project using docker-compose:

```
services:
  mercure:
    image: dunglas/mercure
    environment:
      - CORS_ALLOWED_ORIGINS=https://localhost:8000
      - JWT_KEY=***
      - PUBLISH_ALLOWED_ORIGINS=*
    ports:
      - "80:80"
```

When I go to http://localhost, I get 'Welcome to Mercure!', but http://localhost/hub gives me a 404 Not Found.

```
time=“2019-11-08T09:47:32Z” level=info msg=“Mercure started” addr= protocol=http
172.18.0.1 - - [08/Nov/2019:09:47:47 +0000] “GET /hub HTTP/1.1” 404 19 “” “Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36”
```

Any idea?
