### ISSUE TITLE
CORS_ALLOWED_ORIGINS Multiple origins format?

### ISSUE THREAD

**Issue by byhoratiss** [dunglas/mercure#220]
With the last version upgrade I noticed (not in a nice way) that the "/hub" endpoint changed. No big deal about it.

But with multiple origins it just fails every attempt.
This is my docker-compose service definition:

```
version: '3.7'
  mercure:
    image: dunglas/mercure
    environment:
      - CORS_ALLOWED_ORIGINS=https://mysite.local,http://localhost
```
I already tried with regular expression but failed again.
It just fails to use multiple origins, so my question is: what is the right format?

@teohhanhui I hope you can give me a hint, sorry to tag you.
