### ISSUE TITLE
Traefik and https 

### ISSUE THREAD

**Issue by onEXHovia** [dunglas/mercure#227]
✋ Trying to add mercure to the working project and I’m not completely understanding how to configure https. Wildcard certificates get traefik via provider cloudflare. 

This configuration works http.

```
# .env
MERCURE_ALLOW_ANONYMOUS=1
MERCURE_CORS_ALLOWED_ORIGINS=*
MERCURE_PUBLISH_ALLOWED_ORIGINS=*
MERCURE_PUBLISHER_JWT_KEY=!ChangeMe!
MERCURE_SUBSCRIBER_JWT_KEY=!ChangeMe!
MERCURE_HOST=mercure-dev.domain.ru
MERCURE_DEMO=1
```
```
 docker-compose.yaml
 ....
  mercure:
    build:
      context: .
      target: mercure
    labels:
      - "traefik.frontend.rule=Host:${MERCURE_HOST}"
      - "traefik.docker.network=${NETWORK_PROXY}"
      - "traefik.enable=true"
    environment:
      ALLOW_ANONYMOUS: ${MERCURE_ALLOW_ANONYMOUS}
      PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      PUBLISH_ALLOWED_ORIGINS: ${MERCURE_PUBLISH_ALLOWED_ORIGINS}
      CORS_ALLOWED_ORIGINS: ${MERCURE_CORS_ALLOWED_ORIGINS}
      DEMO: ${MERCURE_DEMO}
    networks:
      - default
      - proxy
  ....
```

When connect via https eventsource have status pending 

```
    <script type="application/javascript">
      var url = new URL('https://mercure-dev.domain.ru/.well-known/mercure');
      url.searchParams.append('topic', 'test');
      var eventSource = new EventSource(url);
      eventSource.onmessage = e => console.log(e);
    </script>
``` 
<img width="2121" alt="Screenshot at Jan 03 18-44-52" src="https://user-images.githubusercontent.com/3332033/71726589-5e764e00-2e59-11ea-9c6e-4c5b1a612abd.png">

The logs display the following:

```
mercure_1        | time="2020-01-03T13:41:49Z" level=info msg="Mercure started" addr= protocol=http
mercure_1        | time="2020-01-03T13:41:59Z" level=info msg="New subscriber" remote_addr="172.18.0.2:41142" subscriber_topics="[test]"
```

Mercure see a new subscriber but does not return response.
