### ISSUE TITLE
API Platform Mercure Subscriber

### ISSUE THREAD

**Issue by castroCrea** [dunglas/mercure#268]
Hello,
I'm searching how to send push to specific target depending of parent object owners

So I create Authorization Mercure JWT token with a subscriber different form each user depending on user uuid like that:

```
<?php 

namespace App\Security\Mercure;

use App\Entity\User;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key;
use Symfony\Component\WebLink\Link;
use Symfony\Component\DependencyInjection\ContainerInterface;

class JWTMercureToken 
{
    private $container;

    public function __construct(ContainerInterface $container) {
        $this->container = $container;
    }

    public function getMercureJWT(string $uuid): string
    {
        $token = (new Builder())
            // set other appropriate JWT claims, such as an expiration date
            ->withClaim('mercure', ['subscribe' => ["$uuid"]]) // could also include the security roles, or anything else
            ->expiresAt((time() + 3600)) // Configures the expiration time of the token (exp claim)
            ->getToken(new Sha256(), new Key($this->container->getParameter('mercure_secret_key'))); // don't forget to set this parameter! Test value: aVerySecretKey

        return $token;
       
    }
}
```  

And then My api platform config is 

```
App\Entity\Item:
    attributes:
        mercure: true
        pagination_client_items_per_page: true
        normalization_context:
            groups: ["action:read"]
    itemOperations:
        get:
            access_control: 'is_granted("IS_ADMIN")'
        put:
            access_control: 'is_granted("IS_AUTHENTICATED_FULLY") and object.getAuthor() == user'
            denormalization_context:
                groups: ["action:write"]
```

So for param ***mercure***
I have tried 

```mercure: "object.getParent().getUsers()"```

But I found out that this parameters it's more who should push in mercure 

In case it wasn't that I tried to add a new property in my entity that match the ***subscribe*** format that is in my mercure jwt token
and then this in the config (getTargets() is and array of user uuid)

```mercure: "object.getTargets()"```

and 

```mercure: "{targets: object.getTargets()}"```

```
        mercure:
            targets: "object.getTargets()"
```

I can't find anywhere how to set the targets for mercure to know to who to push each object.

Can you give me a little help ?
