### ISSUE TITLE
Target IRI wildcards

### ISSUE THREAD

**Issue by bobvandevijver** [dunglas/mercure#291]
I cannot seem to get target wildcards to work.

When I have the following body in the publisher JWT:
```json
{
  "mercure": {
    "publish": [
      "https://domain/{+anything}"
    ]
  }
}
```

I'm not allowed publish (401) to the target `https://domain/test`, while the IRI does match (at least, according to the [tester](http://uri-template-tester.herokuapp.com/?matchTemplate=https%3A%2F%2Fdomain%2F%7B%2Banything%7D&matchURI=https%3A%2F%2Fdomain%2Ftest). 

If I set the full target in the publisher JWT, it is accepted.

I'm using the latest mercure docker image, with the following configuration:
```yaml
version: "3"

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: "mercure"
    environment:
      - PUBLISHER_JWT_KEY=somePubKey
      - SUBSCRIBER_JWT_KEY=someSubKey
      - ADDR=:3000
      - USE_FORWARDED_HEADERS
      - CERT_FILE=/certs/certificate.pem
      - KEY_FILE=/certs/key.pem
    volumes:
      - ./certs:/certs
    ports:
      - "3000:3000"
```

Am I doing anything wrong, or is this simply not supported (yet)?
