### ISSUE TITLE
How to use Mercure with RabbitMq ?

### ISSUE THREAD

**Issue by bastien70** [dunglas/mercure#409]
Hello, I am looking to use Mercury with RabbitMQ. This is the first time that I have used Mercury as well as RabbitMQ so I am not yet good.

Here is where I am: 

I've installed Mercure, and Messenger.

**Messenger.yaml:**

```yaml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
             failed: '%env(MESSENGER_TRANSPORT_FAILED_DSN)%'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
```

**.env**

```
MERCURE_PUBLISH_URL=http://localhost:3000/.well-known/mercure
MERCURE_JWT_TOKEN=aVerySecretKey
MESSENGER_TRANSPORT_DSN=amqp://bastien:mypassword@localhost:5672/%2f/messages
MESSENGER_TRANSPORT_FAILED_DSN=amqp://bastien:mypassword@localhost:5672/%2f/failed
```

In my controller, I've : 

```php
    /**
     * @Route("/ping", name="ping", methods={"POST"})
     */
    public function ping(MessageBusInterface $bus)
    {
        $update = new Update("http://monsite.com/ping", "[]");
        $bus->dispatch($update);
        return $this->redirectToRoute('home');
    }
```

I launched Mercury. And the action I took seems to work fine with the basic settings, without Messenger. Then I added Messenger, and in my controller function, so I placed the Update object in the MessageBusInterface.

So I tested again. And the ping works! But it does not go through rabbitMQ at all, so we would have sync and not async processing.

Did I do something wrong or forget something?
