### ISSUE TITLE
How to set a custom CERT file and key properly ?

### ISSUE THREAD

**Issue by ablond** [dunglas/mercure#41]
When I specified the CERT_FILE and CERT_KEY, mercure throw an error :  
`level=error msg="open : no such file or directory"`

Here's my config docker-compose.yml
```
mercure:
    image: dunglas/mercure
    environment:
      - CERT_FILE=/cert/cert.crt
      - CERT_KEY=/cert/cert.key
      - JWT_KEY=MyJwtSecret
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
    expose:
      - 443
    volumes:
      - ./docker/mercure/cert.crt:/cert/cert.crt
      - ./docker/mercure/cert.key:/cert/cert.key
```

Do you have an idea of what is happening ?
