### ISSUE TITLE
Caddy version with Traefik 2

### ISSUE THREAD

**Issue by back-2-95** [dunglas/mercure#461]
I added Mercure for a local development tool chain we use (portainer, traefik etc).

```
  mercure:
    image: dunglas/mercure:latest
    container_name: "${PREFIX}-mercure"
    command: "caddy run -config /etc/caddy/Caddyfile.dev"
    environment:
      SERVER_NAME: "mercure.${DOCKER_DOMAIN}"
      MERCURE_PUBLISHER_JWT_KEY: dev_key
      MERCURE_SUBSCRIBER_JWT_KEY: dev_key
    labels:
      traefik.enable: true
      traefik.http.routers.mercure.entrypoints: https
      traefik.http.routers.mercure.rule: "Host(`mercure.${DOCKER_DOMAIN}`)"
      traefik.http.routers.mercure.tls: true
      traefik.http.services.mercure.loadbalancer.server.port: 443
```

Using port 443 will get this:

```
Client sent an HTTP request to an HTTPS server.
```

Using port 80 will result `ERR_TOO_MANY_REDIRECTS`

Any idea?

**Comment by julienfollow** [comment]
Same error with trafiik ... i don't know why ...

**Comment by dunglas** [comment]
I don't use Traefik that much but according to the error it's because Traefik is handling the TLS connection, but Caddy is still in HTTPS mode.

You should try to disable the HTTPS support of Caddy. To do so, you can explicitly add `localhost:80` at the first line of the Caddyfile. If you use the default Caddyfile we provide, you can also set the `SERVER_NAME` environment variable to `localhost:80`.

**Comment by back-2-95** [comment]
Thank you, I'll try that.

I'm not familiar with Caddy so I think I tried everything else to change https>http but that line change I did not try.

**Comment by back-2-95** [comment]
I changed to

```
mercure:
    image: dunglas/mercure:latest
    container_name: "${PREFIX}-mercure"
    command: "caddy run -config /etc/caddy/Caddyfile.dev"
    environment:
      SERVER_NAME: "localhost:80"
      MERCURE_PUBLISHER_JWT_KEY: dev_key
      MERCURE_SUBSCRIBER_JWT_KEY: dev_key
    labels:
      traefik.enable: true
      traefik.http.routers.mercure.entrypoints: https
      traefik.http.routers.mercure.rule: "Host(`mercure.${DOCKER_DOMAIN}`)"
      traefik.http.routers.mercure.tls: true
      traefik.http.services.mercure.loadbalancer.server.port: 80
```

Now it gives empty 200 OK responses from https://mercure.${DOCKER_DOMAIN} or https://mercure.${DOCKER_DOMAIN}/.well-known/mercure/ui/

Logs from the Mercure container after those ^^ requests:

```
{"level":"info","ts":1612859656.3541946,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile.dev","config_adapter":""}


{"level":"info","ts":1612859656.3564367,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}


{"level":"info","ts":1612859656.3567033,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}


{"level":"info","ts":1612859656.3569474,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000409110"}


{"level":"debug","ts":1612859656.3683708,"logger":"http","msg":"starting server loop","address":"[::]:80","http3":true,"tls":false}


{"level":"info","ts":1612859656.3686109,"logger":"tls","msg":"cleaned up storage units"}


{"level":"info","ts":1612859656.368702,"msg":"autosaved config","file":"/config/caddy/autosave.json"}


{"level":"info","ts":1612859656.3687165,"msg":"serving initial configuration"}


{"level":"info","ts":1612859659.9985914,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"172.18.0.8:58144","proto":"HTTP/1.1","method":"GET","host":"mercure.docker.sh","uri":"/","headers":{"X-Forwarded-Host":["mercure.docker.sh"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["172.18.0.1"],"Accept":["*/*"],"User-Agent":["HTTPie/2.3.0"],"Accept-Encoding":["gzip, deflate"],"X-Forwarded-For":["172.18.0.1"],"X-Forwarded-Port":["443"],"X-Forwarded-Server":["6bc99a392194"]}},"common_log":"172.18.0.8 - - [09/Feb/2021:08:34:19 +0000] \"GET / HTTP/1.1\" 0 0","duration":0.0000066,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}


{"level":"info","ts":1612859670.5201094,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"172.18.0.8:58144","proto":"HTTP/1.1","method":"GET","host":"mercure.docker.sh","uri":"/.well-known/mercure/ui/","headers":{"Accept":["*/*"],"X-Forwarded-Proto":["https"],"User-Agent":["HTTPie/2.3.0"],"Accept-Encoding":["gzip, deflate"],"X-Forwarded-For":["172.18.0.1"],"X-Forwarded-Host":["mercure.docker.sh"],"X-Forwarded-Port":["443"],"X-Forwarded-Server":["6bc99a392194"],"X-Real-Ip":["172.18.0.1"]}},"common_log":"172.18.0.8 - - [09/Feb/2021:08:34:30 +0000] \"GET /.well-known/mercure/ui/ HTTP/1.1\" 0 0","duration":0.0000088,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
```
