### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK for "https://localhost:8000/.well-known/mercure".

### ISSUE THREAD

**Issue by giantthinker** [dunglas/mercure#473]
Hello, I cannot get pass this error on a Windows 10 computer. Any hints?
Thanks.

**Comment by ochov1** [comment]
I have the same issue

**Comment by ochov1** [comment]
In the file vendor/symfony/mercure/src/Publisher.php you must add in the __invoke method, your return must look like this

```
        return $this->httpClient->request('POST', $this->hubUrl, [
            'auth_bearer' => $jwt,
            'body' => $this->buildQuery($postData),
            'verify_peer' => false
        ])->getContent();
```

so you must add the last 

` 'verify_peer' => false`

have a nice day.

**Comment by oprichnik** [comment]
You can configure the defaultOptions of the Symfony http client in the dev environment like this:
```
# config/packages/dev/framework.yaml

framework:

...

  http_client:
    default_options:
      verify_peer: false
```
