### ISSUE TITLE
Getting always 401 when using RSA public keys

### ISSUE THREAD

**Issue by syntaxgirl** [dunglas/mercure#490]
I followed the documentation and generated public/private keys.

```
ssh-keygen -t rsa -b 4096 -m PEM -f publisher.key
openssl rsa -in publisher.key -pubout -outform PEM -out publisher.key.pub

ssh-keygen -t rsa -b 4096 -m PEM -f subscriber.key
openssl rsa -in subscriber.key -pubout -outform PEM -out subscriber.key.pub
```

Then I used docker compose file from documentation, and added these keys

version: "3.7"

```
services:
  caddy:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '$(cat publisher.key.pub)'
      MERCURE_PUBLISHER_JWT_ALG: 'RS256'
      MERCURE_SUBSCRIBER_JWT_KEY: '$(cat publisher.key.pub)'
      MERCURE_SUBSCRIBER_JWT_ALG: 'RS256'
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
```

unfortunately after container starts up, each request ends up with 401 code. Anyone know why?

Also I tried to run it as

```
MERCURE_PUBLISHER_JWT_KEY=$(cat publisher.key.pub) \
MERCURE_PUBLISHER_JWT_ALG=RS256 \
MERCURE_SUBSCRIBER_JWT_KEY=$(cat subscriber.key.pub) \
MERCURE_SUBSCRIBER_JWT_ALG=RS256 \
./mercure run
```

I get

```
2021/03/31 23:38:13 /!\ This Mercure binary is deprecated, use the binary based on Caddy Server instead! See https://mercure.rocks/docs/UPGRADE
2021/03/31 23:38:13 invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined
panic: invalid config: one of "jwt_key" or "publisher_jwt_key" configuration parameter must be defined
```

I just noticed in the docker logs
`unable to parse JWT: unable to parse RSA public key: Invalid Key: Key must be a PEM encoded PKCS1 or PKCS8 key`

And when I do use pem public key 

```
      MERCURE_PUBLISHER_JWT_KEY: 'cat public.pub'
      MERCURE_PUBLISHER_JWT_ALG: 'RS256'
      MERCURE_SUBSCRIBER_JWT_KEY: 'cat public.pub'
      MERCURE_SUBSCRIBER_JWT_ALG: 'RS256'
```

I still get the same error.

Update:
I was able to get a different error in the log:

`{"level":"info","ts":1617228914.157526,"logger":"http.handlers.mercure","msg":"Topic selectors not matched, not provided or authorization error","remote_addr":"172.17.0.1:35892","error":"unable to parse JWT: key is of invalid type"}`

And this was my JWT token

`eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTcyMjg4MjQsImV4cCI6MTYxNzIzMjQyNCwicm9sZXMiOltdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20iLCJpcCI6IjEyNy4wLjAuMSIsIm1lcmN1cmUiOnsicHVibGlzaCI6WyIqIl0sInN1YnNjcmliZSI6WyJodHRwczpcL1wvZXhhbXBsZS5jb21cL215LXByaXZhdGUtdG9waWMiLCJ7c2NoZW1lfTpcL1wveytob3N0fVwvZGVtb1wvYm9va3NcL3tpZH0uanNvbmxkIiwiXC8ud2VsbC1rbm93blwvbWVyY3VyZVwvc3Vic2NyaXB0aW9uc3tcL3RvcGljfXtcL3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOlwvXC9leGFtcGxlLmNvbVwvdXNlcnNcL2R1bmdsYXMiLCJyZW1vdGVBZGRyIjoiMTI3LjAuMC4xIn19fQ.jmhDQOGgzC8LpOfZLX4weoZaoGKVF2DEZDHytCUIGdDGOBeNT_45cHUQf3uK2uTnjnJRCc-c3HRNBtzYxwevQpAtgDG5w7f0FOrlMyxq89JJpE_ddoWIfNWstTqiKOjgQ4N6OerkVoa-V64S4uayajew4N4GTtft1ljlBMM67WoBXoL4Jtkw4F2PxVLFp1qCaKQdWiUnJxrx5P32wmS7jwAAk2ktMBZCHGFNii4ekiqEMV9_nsY34Num8tf7t7JzOygAV9YLCoIv6rhAtXT8i9PFmo7kIuN2vyEhmt7vvOW5QHjDoW6b3y0fK1uKkhezknPg04CGMNpVps2qzHtHuCtMG3CYoWSm65-Ak9xui5eoemf6EtsHYX0AJoXFadC-sus1-CTUoG14LpacLfuV7vl_IQfGxczRZViygWnekL8AIDvAHRkqL6Nqi451FAcKuSr9HaCc9nYCiWC9Pz0CIJ28gpg15lZHJ5-p4UOGsyFWUMMVleJzptpurLsQsIYhZ3eCllijpUc36Pf5Cab4OSSDN3l2c3PJNtuVmnbeIL8WvHMFGYwrmRfVGXOn0lpfG3tttXp2kOJ9C4-6i50a13JYWpKuTleXimDvMYl_P7Sw3YgBMIfLVP2NslnS5UF3iSgKd4ANzPqGDPcE0zGanzr-OKnrAyFt-tjtGIpDGgA`

But I do not see anything wrong there.
