### ISSUE TITLE
Can't get rid of "Connection closed"

### ISSUE THREAD

**Issue by PatrykCysarz** [dunglas/mercure#526]
Hi,

I have issue similiar to this one - https://github.com/dunglas/mercure/issues/464. Except timeout is occuring after ~1min most of the time, and my connection isn't reopening.
```
Connection open at: 10:17:49 
Connection error at: 10:18:26
```

Am I doing something wrong? Here's minimal example to reproduce this:

docker-compose.yml
```
version: "3.1"
services:

  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: '!ChangeMe!'
      CORS_ALLOWED_ORIGINS: '*'
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: 'http://localhost:3000'
      MERCURE_EXTRA_DIRECTIVES: |
        write_timeout 0s
    ports:
      - 7777:80
```
mercure.html:
```
<script>
const url = new URL("http://172.17.0.1:7777/.well-known/mercure");
url.searchParams.append('topic', '/status');

const eventSource = new EventSource(url, { withCredentials: true });

eventSource.addEventListener('open', evt => {
  const now = new Date();
  console.log(`Connection open at: ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`);
});

eventSource.addEventListener('error', evt => {
  const now = new Date();
  console.log(`Connection error at: ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}`);
});
eventSource.onmessage = e => console.log(e);

</script>
```
