### ISSUE TITLE
Error using mecure on symfony project for https with apache (with docker)

### ISSUE THREAD

**Issue by kayzere** [dunglas/mercure#573]
Hello ^^,
EN
i m facing some probleme in mercure trying to push my projet in production. in http all work good but in https no
so i show you all file can help you to understand my probleme to solve it.
FR 
Je suis confronté à un problème sur mercure en essayant de deployer mon projet en production.  En http tout fonctionne bien mais en https non. Je vous montre tous les fichiers qui peuvent vous aider à comprendre à résoudre le problème.

```
web:
    build: 
      context: .
      target: Symfony_PHP
    container_name: web_symfony
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./project/:/var/www/project:delegated
      - symfony-var:/var/www/project/var/
      - symfony-vendor:/var/www/project/vendor/
    networks:
      - dev
mercure:
    image: dunglas/mercure
    container_name: mercure
    restart: unless-stopped
    environment:
      # SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY}'
    ports:
      - 7001:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dev
```

my apache2 config (docker):
```
<VirtualHost *:80>
    ServerName mysite.net
    ServerAlias project
    DocumentRoot /var/www/project/public

    ErrorLog /var/log/apache2/project_error.log
    CustomLog /var/log/apache2/project_access.log combined
    RewriteEngine on
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mysite.net
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/project/public

        ErrorLog ${APACHE_LOG_DIR}/errorproject.log
        CustomLog ${APACHE_LOG_DIR}/accessproject.log combined

        SSLCertificateFile /etc/ssl/certs/project_certs.crt
        SSLCertificateKeyFile /etc/ssl/private/project_key.key
</VirtualHost>
</IfModule>
```

EN
When i try to connect to 
https://localhost:7001/.well-known/mercure => don't work 
http://localhost:7001/.well-known/mercure => redirect me to http://localhost:80/.well-known/mercure
http://localhost/.well-known/mercure => symfony error no route find
So please help me to solve the problem or tell me what's the problem or how i can run it in https. 

FR
S'il vous plaît, aidez-moi à résoudre le problème ou dites-moi quel est le problème ou comment je peux le faire marcher en https.
thanks. Quel approche je dois utilisé.

thanks you in advance for your help ^^
