### ISSUE TITLE
persistence fails, if storageClass key has value.

### ISSUE THREAD

**Issue by GentianRrafshi** [dunglas/mercure#677]
Hi,

so I want to use mercure via helm with a pvc. For this, I modified the following section of the helmchart:

```
persistence:
  enabled: true
  # -- Mercure Data Persistent Volume Storage Class.
  # If defined, `storageClassName: <storageClass>`
  # If set to `"-"``, `storageClassName: ""``, which disables dynamic provisioning.
  # If undefined (the default) or set to `null`, no `storageClassName` spec is set, choosing the default provisioner.
  storageClass: "netapp-nas"
```
If I then try to deploy mercure into the cluster, I get the following error message:

```
Error: Failed to render chart: exit status 1: Error: YAML parse error on mercure/templates/pvc.yaml: error converting YAML to JSON: yaml: line 15: did not find expected key
```
appears. Am I missing something? I tried several option, even just "-" for testing purposes, but nothing worked. If I comment out `storageClass`, everything works fine.
