### ISSUE TITLE
Datadog and Mercure metrics

### ISSUE THREAD

**Issue by ndousson** [dunglas/mercure#720]
# Context

Mercure Hub: v0.14.2

# Problem

Hi, I recently needed to use Mercure metrics given by the /metrics Caddy endpoint in a Datadog dashboard.

Unfortunately, I was not able to use correctly the value from the **mercure_subscribers** metric.

Datadog only get the gauge and not the counter (_total).

The result was not the expected one (see capture below).

![image](https://user-images.githubusercontent.com/6339309/204328522-e6212f91-0e30-433c-bed1-38ce0eb83b44.png)

As you can see, the value continue to increase indefinitely.

With the **mercure_updates**, I was able to use the counter (no gauge are given) so the result was the expected.

![image](https://user-images.githubusercontent.com/6339309/204328829-74009fcc-80cb-4266-8328-f0ece47ea744.png)

# Test case

I deployed an instance of Mercure in Rancher with the following settings:

```yaml
version: '3'

services:
  mercure-hub:
    image: dunglas/mercure:v0.14.2
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%/metrics",
            "metrics": [
              "mercure_subscribers",
              "mercure_updates",
              "caddy_http_requests"
            ]
          }
        ]
    environment:
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_HUB_JWT_KEY}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_HUB_JWT_KEY}"
      MERCURE_TRANSPORT_URL: bolt:///data/updates.db
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous true
        cors_origins ${CORS_ALLOWED_ORIGINS}
        heartbeat 20s
      GLOBAL_OPTIONS: |
        admin off
      EXTRA_DIRECTIVES: |
        handle /metrics {
          metrics
        }
      SERVER_NAME: ':80' # Disable native HTTPS of Caddy server
```

I created a new widget in my dashboard and search for the **mercure_subscribers** metric as counter:

![image](https://user-images.githubusercontent.com/6339309/204331080-a06ce02e-1931-4dd9-a0aa-548a8a6abdea.png)

As you can see, only the gauge are present.

I tried locally with a Prometheus + Grafana and I was able to query both metrics: **mercure_subscribers** as a gauge and as a counter

# Expected behavior

Datadog is able to get gauge and counter metric types when both exists.

# Proposition

Try to do something like Caddy:

```
# HELP caddy_http_requests_in_flight Number of requests currently handled by this server.
# TYPE caddy_http_requests_in_flight gauge
caddy_http_requests_in_flight{handler="metrics",server="srv0"} 1
caddy_http_requests_in_flight{handler="subroute",server="srv0"} 1

# HELP caddy_http_requests_total Counter of HTTP(S) requests made.
# TYPE caddy_http_requests_total counter
caddy_http_requests_total{handler="metrics",server="srv0"} 5
caddy_http_requests_total{handler="subroute",server="srv0"} 5
```
