### ISSUE TITLE
Problem to track active subscriptions using the static binary 

### ISSUE THREAD

**Issue by kevinG73** [dunglas/mercure#724]
Hi ,
I use **Symfony 6.0 (PHP 8)** , **API PLATFORM** and mercure , I work on **Arch Linux** , i don't use **docker or Caddy server** for moment .
I downloaded the bin file **mercure v0.14.1** to run the hub with the command :
```sh
JWT_KEY='123456' ADDR='localhost:8010' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS='http://localhost:3000' ./mercure --subscriptions=true --debug -f
```
There is no problem, the hub starts without problem , when a user connects to the hub or even disconnects, it is displayed correctly in the console log . 
I developed a app using **Vue 3** and **typescript** to allow my users to exchange messages , I block because i don't can displaying online users in using mercure , I have read the documentation and see that there is a way to do this using Subscription Events .
But it doesn't work . I start my vuejs application as usual on **port 3000**.
here is a preview of my vue js code
```ts
const url = new URL('http://localhost:8010/.well-known/mercure');
const iriurl = "http://localhost:3000/";
url.searchParams.append('topic', iriurl + uuid.value);
url.searchParams.append('topic', 'subscriptions/' + iriurl + '{id}');
const eventSource = new EventSource(url);
eventSource.onmessage = async function (e: any) {
  console.log("CHECK ACTIVE USER");
}
```
My symfony application is launched on port 8009 and I configured like the documentation :
**mercure.yaml**
```yml
mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
```
.env
```env
MERCURE_URL=http://127.0.0.1:8010/.well-known/mercure
MERCURE_PUBLIC_URL=http://127.0.0.1:8010/.well-known/mercure
MERCURE_JWT_SECRET="123456"
```

Next I opened two instances of firefox one in private mode and the other in the normal , I connected two users and I try each time to disconnect and reconnect the second user but no message in my console firefox to display something but messages sent work.
Please someone could help with any hints ?
