### ISSUE TITLE
Mercure inside docker and behind server host Nginx proxy

### ISSUE THREAD

**Issue by kl3sk** [dunglas/mercure#843]
Hello,

I faced a problem. A create a route to test my update and here is the message

```
fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

Docker config
```yaml
networks:
    web-staging-network:
        driver: bridge

services:
    mercure:
        container_name: mercure
        networks:
            web-staging-network:
        env_file:
            - ./.env
        image: dunglas/mercure:latest
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisDevMercureHubJWTSecretKey!}'
            MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisDevMercureHubJWTSecretKey!}'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://app.domain.com
                use_forwarded_headers "1"
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config

volumes:
    mercure_data:
    mercure_config:
```
Docker override:
```yaml
services:
###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "8181:80"
###< symfony/mercure-bundle ###
```

```nginx
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name hub-preprod.domain.com;

    ssl_certificate path_to_crt;
    ssl_certificate_key path_to_key;

    location / {
        proxy_pass http://localhost:8181;
        proxy_read_timeout 24h;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        ## Be sure to set USE_FORWARDED_HEADERS=1 to allow the hub to use those headers ##
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_log /home/<user>/logs/error-hub.log;
    access_log /home/<user>/logs/access-hub.log;
}
```

On DEV mode (eg: command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev, uncommented) , the UI is accessible, but no update is made and return the above error.

Thanks for any help

_Note: It is a private project_
