### ISSUE TITLE
helm - invalid pvc template for storageClass

### ISSUE THREAD

**Issue by VincentDugard** [dunglas/mercure#893]
hello,

When setting storageClass in helm values, I get this error

`Error: UPGRADE FAILED: failed to create resource: PersistentVolumeClaim in version "v1" cannot be handled as a PersistentVolumeClaim: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`

the reason is that the generated yaml is 

```...
resources:
  requests:
    storage: "1Gi"
    storageClassName: "ssd"
```

but it should be
```
resources:
  requests:
    storage: "1Gi"
storageClassName: "ssd"
```

cf : https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
