### ISSUE TITLE
Error: reading config from file: open /etc/caddy/Caddyfile.dev: no such file or directory

### ISSUE THREAD

**Issue by Chris53897** [dunglas/mercure#919]
I just updated the docker images and now i got the error. Mac M1 Silicon
The last working images was around 14 days old.

`Error: reading config from file: open /etc/caddy/Caddyfile.dev: no such file or directory`

**Comment by sayou** [comment]
I also faced the same problem and I don't know what happened
Which made me change the code to the following

```
mercure:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - 8082:8082
        networks:
            - dev
        environment:
            SERVER_NAME: ':8082'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost
                anonymous
        # Comment the following line to disable the development mode
        #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
```
