### ISSUE TITLE
Please add docker secrets feature support that loads env falues from files

### ISSUE THREAD

**Issue by Arkemlar** [dunglas/mercure#956]
Before:
```yaml
    mercure:
        image: dunglas/mercure
        environment:
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
```

After:
```yaml
    mercure:
        image: dunglas/mercure
        environment:
            MERCURE_PUBLISHER_JWT_KEY_FILE: /run/secrets/mercure_publisher_key
            MERCURE_SUBSCRIBER_JWT_KEY_FILE: /run/secrets/mercure_subscriber_key
        secrets:
            - source: mercure_publisher_key
            - source: mercure_subscriber_key

secrets:
    mercure_publisher_key:
        file: docker/secrets/mercure_publisher_key
    mercure_subscriber_key:
        file: docker/secrets/mercure_subscriber_key
```

Image requires entrypoint with [file_env()](https://github.com/BretFisher/node-docker-good-defaults/issues/53) function definition and execution - see [example](https://github.com/matomo-org/docker/blob/master/docker-entrypoint.sh)

Currently there is no entrypoint setting for the image, so no conflict arises as for now.
The problem is container doesn't contain bash so it needs more investigetion
