### ISSUE TITLE
self-signed certificates !!

### ISSUE THREAD

**Issue by xorgxx** [dunglas/mercure#958]
Hi, I’ve been using Mercure for a long time now, and I love it. However, all this time, I’ve had to configure it like this:

```yaml
http_client:
    default_options:
        verify_peer: false
        verify_host: false
```

This applies both in development and, unfortunately, in production as well. I’ve tried for a long time to resolve this issue, but without success!

I’m using Docker (latest version) and Mercure (latest version). Everything works well in both dev and prod, but as soon as I switch to:

```yaml
http_client:
    default_options:
        verify_peer: true
        verify_host: true
```

I get the following error: `"message": "Failed to send an update."`

When I use this command:

```bash
curl --request POST --url https://xxxxxxx.com:9061/.well-known/mercure --header 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.KKPIikwUzRuB3DTpVw6ajzwSChwFw5omBMmMcWKiDcM' --header 'content-type: application/x-www-form-urlencoded' --data topic=https://example.com/my-private-topic --data 'data={"text":"My text value"}'
```
It returns: `urn:uuid:47f74e92-4092-465a-956d-4fea867abfb9`

here my config :
```
# docker-compose.yml
version: "3.9"

services:
  caddy:
    image: dunglas/mercure
    restart: unless-stopped

    container_name: mercure-update
    #environment:
      # Uncomment the following line to disable HTTPS
      #SERVER_NAME: ':80'
      #MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      #MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    # Uncomment the following line to enable the development mode
    command:  caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    ports:
      - "9060:80"
      - "9061:443"

    volumes:
      - /volume1/docker/mercure/xxxxxx:/etc/caddy
      - /volume1/docker/mercure/xxxxxx/ssl:/etc/xxxxxx/ssl
```

```
# Learn how to configure the Mercure.rocks Hub on https://mercure.rocks/docs/hub/config
{
    # Debug mode (disable it in production!)
    #debug
    email xorg@i2p.i2p
    # HTTP/3 support
    #servers {
    #    protocol {
    #        experimental_http3
    #    }
    #}
}

{$SERVER_NAME:xxxxxx.com}:443
# using self-signed 
tls /etc/xxxxxx/ssl/RSA-cert.pem /etc/xxxxxx/ssl/RSA-privkey.pem
log
route {

    redir / /.well-known/mercure/ui/
    encode gzip

    mercure {

        # Enable the demo endpoint (disable it in production!)
        demo

        # Publisher JWT key
        publisher_jwt "!ChangeThisMercureHubJWTSecretKey!"

        # Subscriber JWT key
        subscriber_jwt "!ChangeThisMercureHubJWTSecretKey!"
       
        publish_origins *

        cors_origins *

        # Allow anonymous subscribers (double-check that it's what you want)
        anonymous

        # Enable the subscription API (double-check that it's what you want)
        subscriptions

    }

    respond "Not Found" 404
}
```
```
mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
```

It seems that the Docker server images are working properly. The certificates on the Mercure server are from Let's Encrypt, the development application uses OpenSSL, and the production application uses Let's Encrypt.

So, my question is: Does Mercure support self-signed certificates in both development AND production environments?

thank.

**Comment by dunglas** [comment]
If you can access the hub in HTTPS using a browser or `curl`, this is a problem in your PHP container.

CA certs are probably missing or misconfigured in the PHP container/server. You need to install a bundle (usually the `ca-certificates` package on most distributions), see https://curl.se/docs/sslcerts.html.

**Comment by xorgxx** [comment]
Thank you for the fast answer. I will check this! 🦖

**Comment by xorgxx** [comment]
It seems that it **finally works in development** mode without  `verify_peer: false` with external mercure server.

```
http_client:
    default_options:
        verify_peer: false
        verify_host: false
```
Not really easy to get this working. i will try to explain how i deed with detail that give Dunglas. Thank to him again for helping in this issue.
